services:
  - type: web
    name: telegram-fake-news-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    plan: free
    runtime: python-3.10